#!/bin/bash
set -euo pipefail

pushd $PWD > /dev/null
cd $(dirname $0)
CI_DIR=$PWD
popd > /dev/null

SRC_DIR=$CI_DIR/..

. $CI_DIR/lib/common.sh

QT_ARCH_WINDOWS=win64_mingw
QT_MINGW=tools_mingw1310
QT_MINGW_PATH=mingw1310_64/bin
QT_ARCH_MACOS=clang_64
QT_VERSION=6.8.3

ECM_VERSION=6.11.0

CMAKE_VERSION=3.31.\*
CMAKE_GENERATOR=Ninja

QPROPGEN_VERSION=0.1.\*

add_env_var() {
    echo "export $1=\"$2\"" >> $ENV_FILE
    export $1="$2"
}

prepend_path() {
    if [ ! -d "$1" ] ; then
        die "prepend_path: \"$1\" does not exist"
    fi
    echo "export PATH=$1:\$PATH" >> $ENV_FILE
    export PATH=$1:$PATH
}

if is_windows ; then
    CMAKE_GENERATOR="MinGW Makefiles"
fi

. $CI_DIR/lib/common-dependencies.sh
. $CI_DIR/lib/$OS-dependencies.sh

INST_DIR=$1
mkdir -p $INST_DIR

# Make INST_DIR absolute
pushd $PWD > /dev/null
cd $INST_DIR
INST_DIR=$PWD
popd

if is_windows ; then
    INST_DIR=$(cygpath $INST_DIR)
fi

ENV_FILE=$INST_DIR/env.sh

rm -f $ENV_FILE
touch $ENV_FILE

add_env_var CMAKE_INSTALL_PREFIX $INST_DIR
add_env_var CMAKE_PREFIX_PATH $INST_DIR
add_env_var CMAKE_GENERATOR "$CMAKE_GENERATOR"

main
